//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class DefensiveStats
    {
        public int DefensiveStatsID { get; set; }
        public int PlayerID { get; set; }
        public Nullable<int> Season { get; set; }
        public string Team { get; set; }
        public Nullable<int> GamesPlayed { get; set; }
        public Nullable<int> CombinedTackles { get; set; }
        public Nullable<int> TotalTackles { get; set; }
        public Nullable<int> AssistedTackles { get; set; }
        public Nullable<double> Sack { get; set; }
        public Nullable<int> FumblesForced { get; set; }
        public Nullable<int> FumblesRecovered { get; set; }
        public Nullable<int> FumbleReturnYards { get; set; }
        public Nullable<int> Interceptions { get; set; }
        public Nullable<int> IntReturnYards { get; set; }
        public Nullable<int> IntReturnYardLong { get; set; }
        public Nullable<int> IntTDs { get; set; }
        public Nullable<int> PassesDefended { get; set; }
        public Nullable<int> Stuffs { get; set; }
        public Nullable<int> StuffYards { get; set; }
        public Nullable<int> KicksBlocked { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
