//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsTwitterBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class KickingStats
    {
        public int KickingStatsID { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public Nullable<int> Season { get; set; }
        public string Team { get; set; }
        public Nullable<int> GamesPlayed { get; set; }
        public Nullable<int> FGMade { get; set; }
        public Nullable<int> FGAtt { get; set; }
        public Nullable<int> FG19Yards { get; set; }
        public Nullable<int> FG29Yards { get; set; }
        public Nullable<int> FG39Yards { get; set; }
        public Nullable<int> FG49Yards { get; set; }
        public Nullable<int> FG50Plus { get; set; }
        public Nullable<int> Long { get; set; }
        public Nullable<int> XPM { get; set; }
        public Nullable<int> XPA { get; set; }
        public Nullable<int> Points { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
