//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logger
    {
        public int LoggerID { get; set; }
        public string LogMessage { get; set; }
        public string Result { get; set; }
        public System.DateTime CreatedDate { get; set; }
    }
}
