//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class NFLTeams
    {
        public NFLTeams()
        {
            this.Players = new HashSet<Players>();
        }
    
        public int NFLTeamID { get; set; }
        public string TeamName { get; set; }
        public string TeamAbbrev { get; set; }
        public string TeamLogoPath { get; set; }
    
        public virtual ICollection<Players> Players { get; set; }
    }
}
