//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class PassingStats
    {
        public int PassingStatsID { get; set; }
        public int PlayerID { get; set; }
        public int Season { get; set; }
        public string Team { get; set; }
        public int GamesPlayed { get; set; }
        public int Completions { get; set; }
        public int Attempts { get; set; }
        public int Yards { get; set; }
        public int Touchdowns { get; set; }
        public int Long { get; set; }
        public int Interceptions { get; set; }
        public int Fumbles { get; set; }
        public Nullable<double> QBRating { get; set; }
        public double PasserRating { get; set; }
        public string TestAvg { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
