//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace StatsTwitterBot
{
    using System;
    using System.Collections.Generic;
    
    public partial class Players
    {
        public Players()
        {
            this.DefensiveStats = new HashSet<DefensiveStats>();
            this.KickingStats = new HashSet<KickingStats>();
            this.PassingStats = new HashSet<PassingStats>();
            this.PuntingStats = new HashSet<PuntingStats>();
            this.ReceivingStats = new HashSet<ReceivingStats>();
            this.ReturnStats = new HashSet<ReturnStats>();
            this.RushingStats = new HashSet<RushingStats>();
            this.ScoringStats = new HashSet<ScoringStats>();
        }
    
        public int PlayerID { get; set; }
        public string PlayerName { get; set; }
        public string Team { get; set; }
        public string ImageURL { get; set; }
        public string ImagePath { get; set; }
        public Nullable<int> TeamID { get; set; }
        public string Position { get; set; }
        public Nullable<bool> IsPlayer { get; set; }
        public string Number { get; set; }
    
        public virtual ICollection<DefensiveStats> DefensiveStats { get; set; }
        public virtual ICollection<KickingStats> KickingStats { get; set; }
        public virtual NFLTeams NFLTeams { get; set; }
        public virtual ICollection<PassingStats> PassingStats { get; set; }
        public virtual ICollection<PuntingStats> PuntingStats { get; set; }
        public virtual ICollection<ReceivingStats> ReceivingStats { get; set; }
        public virtual ICollection<ReturnStats> ReturnStats { get; set; }
        public virtual ICollection<RushingStats> RushingStats { get; set; }
        public virtual ICollection<ScoringStats> ScoringStats { get; set; }
    }
}
