//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TwitterTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class PuntingStats
    {
        public int PuntingStatsID { get; set; }
        public Nullable<int> PlayerID { get; set; }
        public Nullable<int> Season { get; set; }
        public string Team { get; set; }
        public Nullable<int> GamesPlayed { get; set; }
        public Nullable<int> Punts { get; set; }
        public Nullable<int> Long { get; set; }
        public Nullable<int> PuntYards { get; set; }
        public Nullable<int> BlockedPunts { get; set; }
        public Nullable<int> Touchbacks { get; set; }
        public Nullable<int> Inside20 { get; set; }
    
        public virtual Players Players { get; set; }
    }
}
